/* Generated By:JJTree: Do not edit this line. AnnotationTypeDeclaration.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class AnnotationTypeDeclaration extends SimpleNode {
  public AnnotationTypeDeclaration(int id) {
    super(id);
  }

  public AnnotationTypeDeclaration(JavaParser1_7 p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JavaParser1_7Visitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=6e06e181fe5db4855cd31306b4b2b0b1 (do not edit this line) */
