/* Generated By:JJTree: Do not edit this line. AnnotationElement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class AnnotationElement extends SimpleNode {
  public AnnotationElement(int id) {
    super(id);
  }

  public AnnotationElement(JavaParser1_7 p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JavaParser1_7Visitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=d4a76161a01c1da026d9d3b812ac0c38 (do not edit this line) */
