/* Generated By:JJTree: Do not edit this line. AnnotationTypeElementDeclaration.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class AnnotationTypeElementDeclaration extends SimpleNode {
  public AnnotationTypeElementDeclaration(int id) {
    super(id);
  }

  public AnnotationTypeElementDeclaration(JavaParser1_7 p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JavaParser1_7Visitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=59df87cefe099c927aa1d2e94d101888 (do not edit this line) */
