/* Generated By:JJTree: Do not edit this line. ArrayInitializer.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ArrayInitializer extends SimpleNode {
  public ArrayInitializer(int id) {
    super(id);
  }

  public ArrayInitializer(JavaParser1_7 p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JavaParser1_7Visitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=3b70f5c0b2004ecb1fdc771a3f63aa9d (do not edit this line) */
