/* Generated By:JJTree: Do not edit this line. ArrayCreatorRest.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ArrayCreatorRest extends SimpleNode {
  public ArrayCreatorRest(int id) {
    super(id);
  }

  public ArrayCreatorRest(JavaParser1_7 p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JavaParser1_7Visitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=c212a02ec94a35871bccbe1c2bc3501b (do not edit this line) */
