/* Generated By:JJTree: Do not edit this line. CharacterLiteral.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class CharacterLiteral extends SimpleNode {
  public CharacterLiteral(int id) {
    super(id);
  }

  public CharacterLiteral(JavaParser1_7 p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JavaParser1_7Visitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=53d7952a820a58dc56b819fbe47181e6 (do not edit this line) */
