/* Generated By:JJTree: Do not edit this line. ClassCreatorRest.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ClassCreatorRest extends SimpleNode {
  public ClassCreatorRest(int id) {
    super(id);
  }

  public ClassCreatorRest(JavaParser1_7 p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JavaParser1_7Visitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=e32c70854e74e47a05b2e8053b4312cd (do not edit this line) */
