/* Generated By:JJTree: Do not edit this line. ClassOrInterfaceDeclaration.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ClassOrInterfaceDeclaration extends SimpleNode {
  public ClassOrInterfaceDeclaration(int id) {
    super(id);
  }

  public ClassOrInterfaceDeclaration(JavaParser1_7 p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JavaParser1_7Visitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=1a72ac7afd80f971caba638469a220db (do not edit this line) */
