/* Generated By:JJTree: Do not edit this line. ClassBodyDeclaration.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ClassBodyDeclaration extends SimpleNode {
  public ClassBodyDeclaration(int id) {
    super(id);
  }

  public ClassBodyDeclaration(JavaParser1_7 p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JavaParser1_7Visitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=4aabaae59dbd4bda02cf57ea8dc6e7fd (do not edit this line) */
