/* Generated By:JJTree: Do not edit this line. ConstructorDeclaratorRest.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ConstructorDeclaratorRest extends SimpleNode {
  public ConstructorDeclaratorRest(int id) {
    super(id);
  }

  public ConstructorDeclaratorRest(JavaParser1_7 p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JavaParser1_7Visitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=e8a44a5ebc1ce98cad41206d25a91398 (do not edit this line) */
