/* Generated By:JJTree: Do not edit this line. ConstantDeclaratorsRest.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ConstantDeclaratorsRest extends SimpleNode {
  public ConstantDeclaratorsRest(int id) {
    super(id);
  }

  public ConstantDeclaratorsRest(JavaParser1_7 p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JavaParser1_7Visitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=af3ca3168aba23f3fbb0d08e6403a128 (do not edit this line) */
