/* Generated By:JJTree: Do not edit this line. ConstantDeclaratorRest.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ConstantDeclaratorRest extends SimpleNode {
  public ConstantDeclaratorRest(int id) {
    super(id);
  }

  public ConstantDeclaratorRest(JavaParser1_7 p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JavaParser1_7Visitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=970bb705ae83f5820cc19b403dd93320 (do not edit this line) */
