/* Generated By:JJTree: Do not edit this line. ConstantDeclarator.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ConstantDeclarator extends SimpleNode {
  public ConstantDeclarator(int id) {
    super(id);
  }

  public ConstantDeclarator(JavaParser1_7 p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JavaParser1_7Visitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=a123e4744a4456346339c4165e476ef7 (do not edit this line) */
