/* Generated By:JJTree: Do not edit this line. ElementValueArrayInitializer.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ElementValueArrayInitializer extends SimpleNode {
  public ElementValueArrayInitializer(int id) {
    super(id);
  }

  public ElementValueArrayInitializer(JavaParser1_7 p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JavaParser1_7Visitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=27677b131b7b4ed72e6f205143d2ea0d (do not edit this line) */
