/* Generated By:JJTree: Do not edit this line. ElementValuePairs.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ElementValuePairs extends SimpleNode {
  public ElementValuePairs(int id) {
    super(id);
  }

  public ElementValuePairs(JavaParser1_7 p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JavaParser1_7Visitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=dd51d8562b722f7ff6a18f53dc9cfaac (do not edit this line) */
