/* Generated By:JJTree: Do not edit this line. EnumConstants.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class EnumConstants extends SimpleNode {
  public EnumConstants(int id) {
    super(id);
  }

  public EnumConstants(JavaParser1_7 p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JavaParser1_7Visitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=90808d865a4d8a537bb11eab09d88ff9 (do not edit this line) */
