/* Generated By:JJTree: Do not edit this line. ExplicitGenericInvocationSuffix.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ExplicitGenericInvocationSuffix extends SimpleNode {
  public ExplicitGenericInvocationSuffix(int id) {
    super(id);
  }

  public ExplicitGenericInvocationSuffix(JavaParser1_7 p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JavaParser1_7Visitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=85dd3feeed5aaef57f134ec6875bd1a7 (do not edit this line) */
