/* Generated By:JJTree: Do not edit this line. ForVariableDeclaratorsRest.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ForVariableDeclaratorsRest extends SimpleNode {
  public ForVariableDeclaratorsRest(int id) {
    super(id);
  }

  public ForVariableDeclaratorsRest(JavaParser1_7 p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JavaParser1_7Visitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=bc9eb1cebdd8c70847b7438d669e1937 (do not edit this line) */
