/* Generated By:JJTree: Do not edit this line. HasNotEllipsis.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class HasNotEllipsis extends SimpleNode {
  public HasNotEllipsis(int id) {
    super(id);
  }

  public HasNotEllipsis(JavaParser1_7 p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JavaParser1_7Visitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=2e28c07e7801b5f7d992306785d8ecd1 (do not edit this line) */
