/* Generated By:JJTree: Do not edit this line. HasStaticModifier.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class HasStaticModifier extends SimpleNode {
  public HasStaticModifier(int id) {
    super(id);
  }

  public HasStaticModifier(JavaParser1_7 p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JavaParser1_7Visitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=a75c45add1a7a1af3ce0e955cd993477 (do not edit this line) */
