/* Generated By:JJTree: Do not edit this line. InterfaceBodyDeclaration.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class InterfaceBodyDeclaration extends SimpleNode {
  public InterfaceBodyDeclaration(int id) {
    super(id);
  }

  public InterfaceBodyDeclaration(JavaParser1_7 p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JavaParser1_7Visitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=020ea032f389d4a603efd27790c0e9aa (do not edit this line) */
