/* Generated By:JJTree: Do not edit this line. InterfaceMethodDeclaratorRest.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class InterfaceMethodDeclaratorRest extends SimpleNode {
  public InterfaceMethodDeclaratorRest(int id) {
    super(id);
  }

  public InterfaceMethodDeclaratorRest(JavaParser1_7 p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JavaParser1_7Visitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=dac3cfc99b74518c62838f78ee3d8053 (do not edit this line) */
