/* Generated By:JJTree: Do not edit this line. InterfaceGenericMethodDecl.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class InterfaceGenericMethodDecl extends SimpleNode {
  public InterfaceGenericMethodDecl(int id) {
    super(id);
  }

  public InterfaceGenericMethodDecl(JavaParser1_7 p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JavaParser1_7Visitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=02d61bba70855a05863595193f9e7031 (do not edit this line) */
