/* Generated By:JJTree: Do not edit this line. InterfaceMemberDecl.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class InterfaceMemberDecl extends SimpleNode {
  public InterfaceMemberDecl(int id) {
    super(id);
  }

  public InterfaceMemberDecl(JavaParser1_7 p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JavaParser1_7Visitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=d29f9cfcf59e3d59837bc07b784aa976 (do not edit this line) */
