/* Generated By:JJTree: Do not edit this line. LabeledContinue.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class LabeledContinue extends SimpleNode {
  public LabeledContinue(int id) {
    super(id);
  }

  public LabeledContinue(JavaParser1_7 p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JavaParser1_7Visitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=817420166ccc11567b8f3f96a4d605aa (do not edit this line) */
