/* Generated By:JJTree: Do not edit this line. LocalVariableDeclarationStatement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class LocalVariableDeclarationStatement extends SimpleNode {
  public LocalVariableDeclarationStatement(int id) {
    super(id);
  }

  public LocalVariableDeclarationStatement(JavaParser1_7 p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JavaParser1_7Visitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=c5a2eabd05e16dc552dd58327f24cab0 (do not edit this line) */
