/* Generated By:JJTree: Do not edit this line. NonEmptyInterfaceDeclaration.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class NonEmptyInterfaceDeclaration extends SimpleNode {
  public NonEmptyInterfaceDeclaration(int id) {
    super(id);
  }

  public NonEmptyInterfaceDeclaration(JavaParser1_7 p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JavaParser1_7Visitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=696723c009361a2f73d6cda77f99b188 (do not edit this line) */
