/* Generated By:JJTree: Do not edit this line. NonWildcardTypeArguments.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class NonWildcardTypeArguments extends SimpleNode {
  public NonWildcardTypeArguments(int id) {
    super(id);
  }

  public NonWildcardTypeArguments(JavaParser1_7 p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JavaParser1_7Visitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=a7d10d13f5c58bcf576b98b06a12fdab (do not edit this line) */
