/* Generated By:JJTree: Do not edit this line. NonWildcardTypeArgumentsOrDiamond.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class NonWildcardTypeArgumentsOrDiamond extends SimpleNode {
  public NonWildcardTypeArgumentsOrDiamond(int id) {
    super(id);
  }

  public NonWildcardTypeArgumentsOrDiamond(JavaParser1_7 p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JavaParser1_7Visitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=c0e66f5b4fffa655e20e7fd711e2e434 (do not edit this line) */
