/* Generated By:JJTree: Do not edit this line. PossibleStaticModifier.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class PossibleStaticModifier extends SimpleNode {
  public PossibleStaticModifier(int id) {
    super(id);
  }

  public PossibleStaticModifier(JavaParser1_7 p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JavaParser1_7Visitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=b45338be2ff0fe7ce01588294e443b50 (do not edit this line) */
