/* Generated By:JJTree: Do not edit this line. SwitchBlockStatementGroups.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class SwitchBlockStatementGroups extends SimpleNode {
  public SwitchBlockStatementGroups(int id) {
    super(id);
  }

  public SwitchBlockStatementGroups(JavaParser1_7 p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JavaParser1_7Visitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=9d1c1bffb52f7cec73a807387085cad2 (do not edit this line) */
