/* Generated By:JJTree: Do not edit this line. SynchronizedStatement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class SynchronizedStatement extends SimpleNode {
  public SynchronizedStatement(int id) {
    super(id);
  }

  public SynchronizedStatement(JavaParser1_7 p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JavaParser1_7Visitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=9d07a03adbae41bc039b83eecb97d150 (do not edit this line) */
