/* Generated By:JJTree: Do not edit this line. UnlabeledBreak.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class UnlabeledBreak extends SimpleNode {
  public UnlabeledBreak(int id) {
    super(id);
  }

  public UnlabeledBreak(JavaParser1_7 p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JavaParser1_7Visitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=05128953d19a0775414e6211ed3beccb (do not edit this line) */
