/* Generated By:JJTree: Do not edit this line. VariableDeclarator.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class VariableDeclarator extends SimpleNode {
  public VariableDeclarator(int id) {
    super(id);
  }

  public VariableDeclarator(JavaParser1_7 p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JavaParser1_7Visitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=cfbee8c68371cf7ab17c6ac411f7b07c (do not edit this line) */
