/* Generated By:JJTree: Do not edit this line. VoidInterfaceMethodDeclaratorRest.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class VoidInterfaceMethodDeclaratorRest extends SimpleNode {
  public VoidInterfaceMethodDeclaratorRest(int id) {
    super(id);
  }

  public VoidInterfaceMethodDeclaratorRest(JavaParser1_7 p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JavaParser1_7Visitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=bc25a936a18834ded6375b6bc65649e8 (do not edit this line) */
